/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as FreeRouteImport } from './routes/free'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as NewBillRouteImport } from './routes/new-bill'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBroadcastsRouteImport } from './routes/admin/broadcasts'
import { Route as AdminHotelsRouteImport } from './routes/admin/hotels'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CustomerPhoneRouteImport } from './routes/customer.$phone'
import { Route as AdminHotelsHotelIdRouteImport } from './routes/admin/hotels/$hotelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRoute = FreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NewBillRoute = NewBillRouteImport.update({
  id: '/new-bill',
  path: '/new-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/admin/broadcasts',
  path: '/admin/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/admin/hotels',
  path: '/admin/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPhoneRoute = CustomerPhoneRouteImport.update({
  id: '/customer/$phone',
  path: '/customer/$phone',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHotelsHotelIdRoute = AdminHotelsHotelIdRouteImport.update({
  id: '/$hotelId',
  path: '/$hotelId',
  getParentRoute: () => AdminHotelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/free': typeof FreeRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/new-bill': typeof NewBillRoute
  '/register': typeof RegisterRoute
  '/revenue': typeof RevenueRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/hotels': typeof AdminHotelsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/$phone': typeof CustomerPhoneRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/free': typeof FreeRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/new-bill': typeof NewBillRoute
  '/register': typeof RegisterRoute
  '/revenue': typeof RevenueRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/hotels': typeof AdminHotelsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/$phone': typeof CustomerPhoneRoute
  '/admin': typeof AdminIndexRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/free': typeof FreeRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/new-bill': typeof NewBillRoute
  '/register': typeof RegisterRoute
  '/revenue': typeof RevenueRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/hotels': typeof AdminHotelsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/$phone': typeof CustomerPhoneRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hotels/$hotelId': typeof AdminHotelsHotelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/customers'
    | '/free'
    | '/login'
    | '/menu'
    | '/new-bill'
    | '/register'
    | '/revenue'
    | '/admin/broadcasts'
    | '/admin/hotels'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/$phone'
    | '/admin/'
    | '/admin/hotels/$hotelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/customers'
    | '/free'
    | '/login'
    | '/menu'
    | '/new-bill'
    | '/register'
    | '/revenue'
    | '/admin/broadcasts'
    | '/admin/hotels'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/$phone'
    | '/admin'
    | '/admin/hotels/$hotelId'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/customers'
    | '/free'
    | '/login'
    | '/menu'
    | '/new-bill'
    | '/register'
    | '/revenue'
    | '/admin/broadcasts'
    | '/admin/hotels'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/$phone'
    | '/admin/'
    | '/admin/hotels/$hotelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  CustomersRoute: typeof CustomersRoute
  FreeRoute: typeof FreeRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  NewBillRoute: typeof NewBillRoute
  RegisterRoute: typeof RegisterRoute
  RevenueRoute: typeof RevenueRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminHotelsRoute: typeof AdminHotelsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CustomerPhoneRoute: typeof CustomerPhoneRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free': {
      id: '/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof FreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-bill': {
      id: '/new-bill'
      path: '/new-bill'
      fullPath: '/new-bill'
      preLoaderRoute: typeof NewBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/admin/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/admin/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$phone': {
      id: '/customer/$phone'
      path: '/customer/$phone'
      fullPath: '/customer/$phone'
      preLoaderRoute: typeof CustomerPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hotels/$hotelId': {
      id: '/admin/hotels/$hotelId'
      path: '/$hotelId'
      fullPath: '/admin/hotels/$hotelId'
      preLoaderRoute: typeof AdminHotelsHotelIdRouteImport
      parentRoute: typeof AdminHotelsRoute
    }
  }
}

interface AdminHotelsRouteChildren {
  AdminHotelsHotelIdRoute: typeof AdminHotelsHotelIdRoute
}

const AdminHotelsRouteChildren: AdminHotelsRouteChildren = {
  AdminHotelsHotelIdRoute: AdminHotelsHotelIdRoute,
}

const AdminHotelsRouteWithChildren = AdminHotelsRoute._addFileChildren(
  AdminHotelsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  CustomersRoute: CustomersRoute,
  FreeRoute: FreeRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  NewBillRoute: NewBillRoute,
  RegisterRoute: RegisterRoute,
  RevenueRoute: RevenueRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminHotelsRoute: AdminHotelsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CustomerPhoneRoute: CustomerPhoneRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
