/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as FreeRouteImport } from './routes/free'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as NewBillRouteImport } from './routes/new-bill'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as CustomerPhoneRouteImport } from './routes/customer.$phone'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRoute = FreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NewBillRoute = NewBillRouteImport.update({
  id: '/new-bill',
  path: '/new-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPhoneRoute = CustomerPhoneRouteImport.update({
  id: '/customer/$phone',
  path: '/customer/$phone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/free': typeof FreeRoute
  '/menu': typeof MenuRoute
  '/new-bill': typeof NewBillRoute
  '/revenue': typeof RevenueRoute
  '/customer/$phone': typeof CustomerPhoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/free': typeof FreeRoute
  '/menu': typeof MenuRoute
  '/new-bill': typeof NewBillRoute
  '/revenue': typeof RevenueRoute
  '/customer/$phone': typeof CustomerPhoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/free': typeof FreeRoute
  '/menu': typeof MenuRoute
  '/new-bill': typeof NewBillRoute
  '/revenue': typeof RevenueRoute
  '/customer/$phone': typeof CustomerPhoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/customers'
    | '/free'
    | '/menu'
    | '/new-bill'
    | '/revenue'
    | '/customer/$phone'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/customers'
    | '/free'
    | '/menu'
    | '/new-bill'
    | '/revenue'
    | '/customer/$phone'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/customers'
    | '/free'
    | '/menu'
    | '/new-bill'
    | '/revenue'
    | '/customer/$phone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  CustomersRoute: typeof CustomersRoute
  FreeRoute: typeof FreeRoute
  MenuRoute: typeof MenuRoute
  NewBillRoute: typeof NewBillRoute
  RevenueRoute: typeof RevenueRoute
  CustomerPhoneRoute: typeof CustomerPhoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free': {
      id: '/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof FreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-bill': {
      id: '/new-bill'
      path: '/new-bill'
      fullPath: '/new-bill'
      preLoaderRoute: typeof NewBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$phone': {
      id: '/customer/$phone'
      path: '/customer/$phone'
      fullPath: '/customer/$phone'
      preLoaderRoute: typeof CustomerPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  CustomersRoute: CustomersRoute,
  FreeRoute: FreeRoute,
  MenuRoute: MenuRoute,
  NewBillRoute: NewBillRoute,
  RevenueRoute: RevenueRoute,
  CustomerPhoneRoute: CustomerPhoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
